#!/usr/bin/env bash
# Snapshot CLI help into docs/reference/cli-help.md (JOE-1717).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
OUT="${ROOT}/docs/reference/cli-help.md"
mkdir -p "$(dirname "$OUT")"

BIN=(cargo run -q -p aurum-stt --)
if command -v aurum >/dev/null 2>&1 && aurum --version 2>/dev/null | grep -q .; then
  # Prefer workspace build for truth against this tree.
  :
fi

{
  echo "# CLI help snapshot"
  echo
  echo "Generated by \`scripts/generate_cli_reference.sh\`. Do not hand-edit."
  echo
  echo '```text'
  cargo run -q -p aurum-stt -- --help
  echo '```'
  echo
  for sub in models batch doctor cache tts cleanup completions man "support-bundle"; do
    echo "## \`aurum ${sub}\`"
    echo
    echo '```text'
    cargo run -q -p aurum-stt -- ${sub} --help 2>/dev/null || cargo run -q -p aurum-stt -- help ${sub}
    echo '```'
    echo
  done
} >"${OUT}"

echo "wrote ${OUT}"
